# Form implementation generated from reading ui file 'page_system.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_systemPage(object):
    def setupUi(self, Form_systemPage):
        Form_systemPage.setObjectName("Form_systemPage")
        Form_systemPage.resize(821, 477)
        self.label = QtWidgets.QLabel(parent=Form_systemPage)
        self.label.setGeometry(QtCore.QRect(90, 120, 541, 211))
        self.label.setObjectName("label")

        self.retranslateUi(Form_systemPage)
        QtCore.QMetaObject.connectSlotsByName(Form_systemPage)

    def retranslateUi(self, Form_systemPage):
        _translate = QtCore.QCoreApplication.translate
        Form_systemPage.setWindowTitle(_translate("Form_systemPage", "Form"))
        self.label.setText(_translate("Form_systemPage", "相机配置、型号管理、是否存图等"))
