# Form implementation generated from reading ui file 'page_data.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_dataPage(object):
    def setupUi(self, Form_dataPage):
        Form_dataPage.setObjectName("Form_dataPage")
        Form_dataPage.resize(683, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_dataPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=Form_dataPage)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(parent=Form_dataPage)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.horizontalLayout.addWidget(self.dateTimeEdit_start)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(parent=Form_dataPage)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.horizontalLayout.addWidget(self.dateTimeEdit_end)
        self.pushButton_select = QtWidgets.QPushButton(parent=Form_dataPage)
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout.addWidget(self.pushButton_select)
        self.pushButton_export = QtWidgets.QPushButton(parent=Form_dataPage)
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout.addWidget(self.pushButton_export)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form_dataPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form_dataPage)
        QtCore.QMetaObject.connectSlotsByName(Form_dataPage)

    def retranslateUi(self, Form_dataPage):
        _translate = QtCore.QCoreApplication.translate
        Form_dataPage.setWindowTitle(_translate("Form_dataPage", "Form"))
        self.comboBox.setItemText(0, _translate("Form_dataPage", "结果表"))
        self.comboBox.setItemText(1, _translate("Form_dataPage", "报警表"))
        self.pushButton_select.setText(_translate("Form_dataPage", "查询"))
        self.pushButton_export.setText(_translate("Form_dataPage", "导出"))
